version: '3'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "3000:3000"

  backend2:
    build:
      context: ./backend2
    ports:
      - "5001:5000"

  frontend:
    build: 
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
      - backend2
