version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:5000"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - flask
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
